export const TechsObject = [
  { value: 'reactjs', label: 'ReactJS' },
  { value: 'nodejs', label: 'NodeJS' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'angularjs', label: 'AngularJS' },
  { value: 'VueJS', label: 'VueJS' },
  { value: 'dart', label: 'Dart' },
  { value: 'flutter', label: 'Flutter' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'rust', label: 'Rust' },
  { value: 'go', label: 'Go' },
  { value: 'lua', label: 'Lua' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'crystal', label: 'Crystal' },
  { value: 'scrum', label: 'Scrum' },
  { value: 'agile', label: 'Agile' },
  { value: 'bussinessagility', label: 'Bussiness Agility' },
  { value: 'shellScript', label: 'Shell Script' },
  { value: 'git', label: 'Git' },
  { value: 'c++', label: 'C++' },
  { value: 'c', label: 'C' },
  { value: 'php', label: 'PHP' },
  { value: 'sql', label: 'SQL' },
  { value: 'pl/sql', label: 'PL/SQL' },
  { value: 'swift', label: 'Swift' },
  { value: 'objectivec', label: 'Objective-C' },
  { value: 'c#', label: 'C#' },
  { value: 'pascal', label: 'Pascal' },
  { value: 'delphi', label: 'Delphi' },
  { value: 'r', label: 'R' },
  { value: 'matlab', label: 'Matlab' },
  { value: 'pearl', label: 'Pearl' },
  { value: 'assembly', label: 'Assembly' },
  { value: 'webAssembly', label: 'Web Assembly' },
  { value: 'visualBasic', label: 'Visual Basic' },
  { value: 'ada', label: 'Ada' },
  { value: 'd', label: 'D' },
  { value: 'fortran', label: 'Fortran' },
  { value: 'clojure', label: 'Clojure' },
  { value: 'erlang', label: 'Erlang' },
  { value: 'eiffel', label: 'Eiffel' },
  { value: 'elm', label: 'Elm' },
  { value: 'f#', label: 'F#' },
  { value: 'groovy', label: 'Groovy' },
  { value: 'haskell', label: 'Haskell' },
  { value: 'julio', label: 'Julia' },
  { value: 'nim', label: 'Nim' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'lisp', label: 'Lisp' },
  { value: 'ocaml', label: 'OCaml' },
  { value: 'reason', label: 'Reason' },
  { value: 'adonisjs', label: 'AdonisJS' },
  { value: 'sqlserver', label: 'SQLServer' },
  { value: 'postgres', label: 'Postgres' },
  { value: 'mysql', label: 'MySQL' },
  { value: 'mongodb', label: 'MongoDB' },
  { value: 'couchdb', label: 'CouchDB' },
  { value: 'tinydb', label: 'TinyDB' },
  { value: 'firebase', label: 'Firebase' },
  { value: 'neo4j', label: 'Neo4j' },
  { value: 'oracledb', label: 'OracleDB' },
  { value: 'cassandra', label: 'Cassandra' },
  { value: 'redis', label: 'Redis' },
];
